### ISSUE TITLE
Retries upon failure, despite the command being unnecessary

### ISSUE THREAD

**Issue by m-chandler** [tesla-local-control/tesla_ble_mqtt_docker#17]
Thanks for setting this up!

One observation I have is that if I send the charging-stop command and it fails due to `not_charging`, tesla_ble_mqtt still retries. I guess there's no great harm, although I believe it chokes up the main loop, preventing other commands from being processed? Could the response be interpreted and the command stopped if the desired state is already set?

```
tesla_ble_mqtt  | Sending command charging-stop, attempt 2/5
tesla_ble_mqtt  | Failed to execute command: car could not execute command: not_charging
tesla_ble_mqtt  | Error calling tesla-control, exit code=1 - will retry in 5 seconds
```

I might get to this myself at some point!

**Comment by raphmur** [comment]
Hi there
Yes Indeed good idea
However, the errors sent by `tesla-control` are not known simply by calling `--help`. It is feasible, but time required to deep dive in the vehicle -command SDK source code to identify all potential cases...

I suggest to keep this as feature request

**Comment by iainbullock** [comment]
Agreed it's a good observation. Let's look at this as time allows in future

**Comment by raphmur** [comment]
#18

**Comment by raphmur** [comment]
See https://github.com/tesla-local-control/tesla-local-control-addon/pull/40

**Comment by iainbullock** [comment]
The latest and probably final update has been released today in the main branch (v.1.1.2). It provides multi-car support (for commands, but not BLE presence), various bug fixes, and enhancements suggested by users.

The project is being migrated to a new one which has three developers (including me). With three of us working on it, we expect to improve functionality, quality, and responsiveness to issues. Check it out at https://github.com/tesla-local-control/tesla-local-control-addon

I will keep this project open until the first release at the new repository.

If your Issue remains unresolved by this release, please review existing Issues at the new repo, and open a new Issue there if required.

I will close the Issue here as the repo will soon be archived. 

Thanks a lot for your input and support on this project.

**Comment by raphmur** [comment]
https://github.com/tesla-local-control/tesla-local-control-addon/pull/40 should solve this. It will break the retries if the car answers `Failed to execute ...`
For me it solved the behaviours:

- setting charging start/stop if the car is already in this state
- setting charging limits if already set

However it may be possible that the car refuses to, for example, take a charging start if charger is not plugged in (not tested).
@m-chandler have you seen suched "crossed" messages? I mean: an error message concerning a different entity from the command sent.

**Comment by m-chandler** [comment]
@raphmur sorry I missed the tag.
I don't really hit that case now, as I'm still using the legacy HTTP API to determine if the car is plugged in (I can't be bothered with the Fleet API).
However yes, if you do try to charge the car when it's not plugged in, it gives you `disconnected` error.
Please note that I'm still on an old dev branch without the improved retry logic (if it's been pushed to this project yet), so the below may no longer be relevant.

```
tesla_ble_mqtt  | Sending command charging-start, attempt 1/5
tesla_ble_mqtt  | Failed to execute command: car could not execute command: disconnected
tesla_ble_mqtt  | Error calling tesla-control, exit code=1 - will retry in 5 seconds
```

**Comment by iainbullock** [comment]
Today's release has much improved retry logic. I will close for now but please reopen if you find further improvements required in the retry logic
